variables:
  GIT_SUBMODULE_STRATEGY: recursive

.template: &template
  before_script:
    - echo "Installing potential dependencies..."


  script:
    - cmake -E make_directory build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_DOCS=OFF ..
    - cmake --build .
    - ctest

build-and-test:gcc:
  image: conanio/gcc9
  <<: *template

build-and-test:clang:
  image: conanio/clang10
  <<: *template


